version: "0.1"

services:
  pds-db:
    image: postgres
    container_name: piscine_datascience_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pds-db:/var/lib/postgresql/data

volumes:
  pds-db: